# --- !Ups
INSERT INTO PUBLIC.ARTICLE(ARTICLE_ID, TITLE, INGRESS, TEXT, AUTHOR, IMAGE_PATH, DATE_MADE) VALUES(1, 'asd', 'sad', STRINGDECODE('<p>Artikkel her</p>\r\n'), 1, NULL, TIMESTAMP '2015-09-13 14:11:56.968');
INSERT INTO PUBLIC.COMMENT(COMMENT_ID, COMMENT, AUTHOR_ID, ARTICLE_ARTICLE_ID, CREATED_DATE) VALUES(1, 'asd', 1, 1, TIMESTAMP '2015-09-13 14:12:07.541');
INSERT INTO PUBLIC.RENDERS(ARTICLE_ID, EVENT_ID) VALUES(1, NULL);
INSERT INTO PUBLIC.USER(ID, USERNAME, FIRST_NAME, SURNAME, MIDDLE_NAME, EMAIL, WEBSITE_URL, PHONE, TITLE, PROFILE_IMAGE_FILE_NAME, GRADUATION_YEAR, STUDENT, BEDKOM, ADMIN, ROOT, SEX, ENROLLED, DATE_OF_BIRTH, LAST_LOGIN) VALUES(1, 'hybrid', '', 'Administrator', NULL, NULL, NULL, NULL, NULL, 'mlg.jpg', 2018, TRUE, TRUE, TRUE, TRUE, STRINGDECODE('\u0000'), NULL, TIMESTAMP '2003-04-01 00:00:00.0', NULL);
